export const cuisineCategory = [
  {
    type: "MILK_TEA",
    name: 'Milk tea',
    slug: 'milk-tea',
    img: 'https://images.summitmedia-digital.com/cosmo/images/2019/07/12/how-to-make-milk-tea-at-home-1562862521.jpg',
  },
  {
    type: "DRINKS",
    name: 'Drinks',
    slug: 'drinks',
    img: 'https://www.superiorwallpapers.com/images/lthumbs/2016-07/11884_Three-delicious-fruit-cocktails-summer-drink.jpg',
  },
  {
    type: "BANH_MI",
    name: 'Banh mi',
    slug: 'banh-mi',
    img: 'https://th.bing.com/th/id/R.9df9776d412b9f20da1b2c31dbdfee76?rik=1CtT%2fRRYFMtbUQ&pid=ImgRaw&r=0',
  },
  {
    type: "FAST_FOOD",
    name: 'Fast food',
    slug: 'fast-food',
    img: 'https://wallpaperaccess.com/full/1306125.jpg',
  },
  {
    type: "RICE",
    name: 'Rice',
    slug: 'rice',
    img: 'https://th.bing.com/th/id/OIP.ADGE7S23fWcKNQrKZAdUJAHaEL?rs=1&pid=ImgDetMain',
  },
  {
    type: "NOODLES",
    name: 'Noodles',
    slug: 'noodles',
    img: 'https://th.bing.com/th/id/OIP.YkAVohgFO7EA4nrZ2sh8rAHaE8?pid=ImgDet&w=474&h=316&rs=1',
  },
  {
    type: "CAKE",
    name: 'Cake',
    slug: 'cake',
    img: 'https://i.pinimg.com/originals/56/1e/c1/561ec1bfe0ca2b878a807039b99a34d3.jpg',
  },
  {
    type: "VEGAN_FOODS",
    name: 'Vegan foods',
    slug: 'vegan-foods',
    img: 'https://th.bing.com/th/id/R.0571c6388470b3528ab5fbe98232fe46?rik=612d1m2PbMvL5g&pid=ImgRaw&r=0',
  },
  {
    type: "BBQ",
    name: 'BBQ',
    slug: 'bbq',
    img: 'https://th.bing.com/th/id/R.6c0941729a63d15d60838d1ab9530304?rik=Fw%2fjknsaeCnMsQ&pid=ImgRaw&r=0',
  },
  {
    type: "THAI_FOOD",
    name: 'Thailand food',
    slug: 'thailand-food',
    img: 'https://th.bing.com/th/id/R.883de27768e4325f1c48e9b0e2d527e2?rik=oENlqK%2bo1%2fWRlQ&pid=ImgRaw&r=0',
  },
  {
    type: "JAPANESE_FOOD",
    name: 'Japanese food',
    slug: 'japanese-food',
    img: 'https://th.bing.com/th?id=OIP.DL_LPBWZzl2WCyai03JlKAHaFj&w=288&h=216&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2',
  },
  {
    type: "KOREAN_FOOD",
    name: 'Korean food',
    slug: 'korean-food',
    img: 'https://th.bing.com/th/id/R.d6c35f4d7f26edd2f863a5317839fbc4?rik=kFfDi1wXv6MjNA&pid=ImgRaw&r=0',
  },
  {
    type: "CHINESE_FOOD",
    name: 'Chinese food',
    slug: 'chinese-food',
    img: 'https://th.bing.com/th/id/OIP.y4SMaZLPp-ntcNFOfR2BsQHaFF?w=500&h=343&rs=1&pid=ImgDetMain',
  },
];
