export const cuisineCategory = [
  {
    type: "MILK_TEA",
    name: 'Milk tea',
    slug: 'milk-tea',
    img: '',
  },
  {
    type: "DRINKS",
    name: 'Drinks',
    slug: 'drinks',
    img: '',
  },
  {
    type: "BANH_MI",
    name: 'Banh mi',
    slug: 'banh-mi',
    img: '',
  },
  {
    type: "FAST_FOOD",
    name: 'Fast food',
    slug: 'fast-food',
    img: '',
  },
  {
    type: "RICE",
    name: 'Rice',
    slug: 'rice',
    img: '',
  },
  {
    type: "NOODLES",
    name: 'Noodles',
    slug: 'noodles',
    img: '',
  },
  {
    type: "CAKE",
    name: 'Cake',
    slug: 'cake',
    img: '',
  },
  {
    type: "VEGAN_FOODS",
    name: 'Vegan foods',
    slug: 'vegan-foods',
    img: '',
  },
  {
    type: "BBQ",
    name: 'BBQ',
    slug: 'bbq',
    img: '',
  },
  {
    type: "THAI_FOOD",
    name: 'Thailand food',
    slug: 'thailand-food',
    img: '',
  },
  {
    type: "JAPANESE_FOOD",
    name: 'Japanese food',
    slug: 'japanese-food',
    img: '',
  },
  {
    type: "KOREAN_FOOD",
    name: 'Korean food',
    slug: 'korean-food',
    img: '',
  },
  {
    type: "CHINESE_FOOD",
    name: 'Chinese food',
    slug: 'chinese-food',
    img: '',
  },
];
